/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.github.sspinc.tixing;

import com.google.zxing.integration.android.IntentIntegrator;
import com.google.zxing.integration.android.IntentResult;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiContext;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

import android.content.Intent;

@Kroll.module(name="Tixing", id="com.github.sspinc.tixing")
public class TixingModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "TixingModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TixingModule(TiContext tiContext) {
		super(tiContext);
	}

  @Kroll.method
  public void initiateScan() {
    logInfo("initiateScan()");
    IntentIntegrator.initiateScan(getTiContext().getActivity());
  }

  protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
    IntentResult scanResult = IntentIntegrator.parseActivityResult(requestCode, resultCode, intent);
    if (scanResult != null) {
      logInfo("Format: " + scanResult.getFormatName());
      logInfo("Barcode: " + scanResult.getContents());
    }
  }

	private void logError(final String msg) {
		Log.e(LCAT, msg);
	}

	private void logInfo(final String msg) {
		Log.i(LCAT, msg);
	}

	private void logDebug(final String msg) {
    Log.d(LCAT, msg);
	}
}
